name: running main.py

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - name: checking_repo
        uses: actions/checkout@v3
      
      - name: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: install_dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: run_main.py
        run: python main.py
